env:
  TERM: xterm-256color

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 100000

window:
  padding:
    x: 20
    y: 15
  dynamic_padding: true
  decorations: buttonless
  opacity: 1
font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic
  size: 16.0
live_config_reload: true

mouse:
  double_click: { threshold: 300 }

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: Key6, mods: Control, chars: "\x1e" }

import:
  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
