#!/bin/bash

install_consular_project () {
	if [ -z "$1" ] # Is parameter 1 zero length?
	then
		echo -e "Error: install_consular_project requires a site name to be specified."
	else
		sed 's/{site}/'$1'/g' ~/.dotfiles/config/consular/default.term > ~/.config/consular/$1.term
	fi
}
