. ~/.dotfiles/config/bash/env
. ~/.dotfiles/config/bash/config
. ~/.dotfiles/config/bash/aliases

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
